#!/usr/bin/env zsh

custom_git_stats() {
  if test -d .git
  then
    local total_insertions=0
    local total_deletions=0

    local data=$(git diff --shortstat --cached; git diff --shortstat)

    echo $data | grep -Po '\d+ (?=insertions?)' | while read value; do
      (( total_insertions = total_insertions + $value ))
    done

    echo $data | grep -Po '\d+ (?=deletions?)' | while read value; do
      (( total_deletions = total_deletions + $value ))
    done

    [[ $total_insertions -eq 0 ]] && total_insertions="" || total_insertions="%F{yellow}+$total_insertions"
    [[ $total_deletions  -eq 0 ]] && total_deletions=""  || total_deletions="%F{red}-$total_deletions"

    echo "$total_insertions $total_deletions"
  fi
}

POWERLEVEL9K_CUSTOM_GIT_STATS="custom_git_stats"
POWERLEVEL9K_CUSTOM_GIT_STATS_BACKGROUND="clear"
POWERLEVEL9K_CUSTOM_GIT_STATS_FOREGROUND="008"


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white'


POWERLEVEL9K_DIR_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="008"
POWERLEVEL9K_DIR_FOREGROUND='010'
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="012"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="012"

POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{008}/%F{cyan}"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"
POWERLEVEL9K_ETC_ICON=""

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"

POWERLEVEL9K_GO_ICON="\uf7b7"
POWERLEVEL9K_GO_VERSION_BACKGROUND='clear'
POWERLEVEL9K_GO_VERSION_FOREGROUND='081'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable_joined vcs_joined custom_git_stats_joined)
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\uf460%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\u2e2b%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='-'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_VCS_HIDE_TAGS=true

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{008}┌%F{clear}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{008}└%F{clear} "

POWERLEVEL9K_NVM_BACKGROUND='clear'
POWERLEVEL9K_NVM_FOREGROUND='green'

POWERLEVEL9K_OS_ICON_BACKGROUND='clear'
POWERLEVEL9K_OS_ICON_FOREGROUND='cyan'

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_DISABLE_RPROMPT=true

typeset -g POWERLEVEL9K_STATUS_{,OK_,ERROR_}BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="001"
POWERLEVEL9K_CARRIAGE_RETURN_ICON="\uf071"

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m}"

typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_BACKGROUND='clear'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED}_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'

POWERLEVEL9K_VCS_UNSTAGED_ICON='%F{008}!%F{008}'
POWERLEVEL9K_VCS_STAGED_ICON=''
#POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
POWERLEVEL9K_VCS_GIT_HOOKS=()
POWERLEVEL9K_SHOW_CHANGESET=false
