#!/usr/bin/env zsh


# Some of these taken here...
# https://coderwall.com/p/pn8f0g/show-your-git-status-and-branch-in-color-at-the-command-prompt


git_stats() {
  if git rev-parse --show-toplevel > /dev/null 2>&1
  then
    setopt local_options BASH_REMATCH
    local total_insertions=0
    local total_deletions=0

    local data=$(git diff --shortstat --cached; git diff --shortstat)

    echo $data | while read value; do
      if [[ ${value} =~ "([[:digit:]]+) insertions.* ([[:digit:]]+) deletions" ]]; then
        (( total_insertions = total_insertions + ${BASH_REMATCH[2]:-0} ))
        (( total_deletions  = total_deletions  + ${BASH_REMATCH[3]:-0} ))
      fi
    done

    [[ $total_insertions -eq 0 ]] && total_insertions="" || total_insertions="%F{yellow}+$total_insertions%F{clear}"
    [[ $total_deletions  -eq 0 ]] && total_deletions=""  || total_deletions="%F{red}-$total_deletions%F{clear}"

    echo "$total_insertions $total_deletions"
  fi
}

custom_git_stats() {
  echo "$(git_stats)"
}

icons=()


POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  # user_joined
  # host_joined
  dir_joined
  vcs_joined
  custom_git_stats_joined
)


POWERLEVEL9K_MODE='nerdfont-complete'

typeset -g POWERLEVEL9K_VCS_{GIT,GITHUB,BITBUCKET}_ICON=""
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_VCS_STAGED_ICON="\b"
POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false
POWERLEVEL9K_VCS_UNSTAGED_ICON="\b"
POWERLEVEL9K_VCS_GIT_HOOKS=()
POWERLEVEL9K_SHOW_CHANGESET=false

POWERLEVEL9K_CUSTOM_GIT_STATS="custom_git_stats"
POWERLEVEL9K_CUSTOM_GIT_STATS_ICON=""
POWERLEVEL9K_CUSTOM_GIT_STATS_SEGMENT_ICON=""
POWERLEVEL9K_CUSTOM_GIT_STATS_BACKGROUND="clear"
POWERLEVEL9K_CUSTOM_GIT_STATS_FOREGROUND="008"

POWERLEVEL9K_HOST_FOREGROUND="grey"
POWERLEVEL9K_HOST_BACKGROUND="clear"
POWERLEVEL9K_HOST_ICON=""
POWERLEVEL9K_USER_ICON=""

POWERLEVEL9K_USER_BACKGROUND="clear"

POWERLEVEL9K_DIR_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="008"
POWERLEVEL9K_DIR_FOREGROUND='010'
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="012"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="012"

POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{008}/%F{cyan}"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"
POWERLEVEL9K_ETC_ICON=""

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"

POWERLEVEL9K_GO_ICON="\uf7b7"
POWERLEVEL9K_GO_VERSION_BACKGROUND='clear'
POWERLEVEL9K_GO_VERSION_FOREGROUND='081'

#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\uf460%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\u2e2b%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='-'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{237}┌%F{clear}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{237}└%F{clear} "


POWERLEVEL9K_NVM_BACKGROUND='clear'
POWERLEVEL9K_NVM_FOREGROUND='green'

POWERLEVEL9K_OS_ICON_BACKGROUND='clear'
POWERLEVEL9K_OS_ICON_FOREGROUND='cyan'

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_DISABLE_RPROMPT=true

typeset -g POWERLEVEL9K_STATUS_{,OK_,ERROR_}BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="001"
POWERLEVEL9K_CARRIAGE_RETURN_ICON="\uf071"

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m}"

typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_BACKGROUND='clear'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED}_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
