#!/usr/bin/env zsh
# shellcheck shell=bash
# shellcheck disable=SC2034

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  virtualenv_joined
  # custom_pyenv_joined
  custom_git_branch_joined
)

POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

icons=()
POWERLEVEL9K_MODE='nerdfont-complete'

typeset -g POWERLEVEL9K_VCS_{GIT,GITHUB,BITBUCKET}_ICON=""
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_VCS_STAGED_ICON="\b"
POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false
POWERLEVEL9K_VCS_UNSTAGED_ICON="\b"
POWERLEVEL9K_VCS_GIT_HOOKS=()
POWERLEVEL9K_SHOW_CHANGESET=false

POWERLEVEL9K_VIRTUALENV_PYTHON_ICON=
POWERLEVEL9K_VIRTUALENV_BACKGROUND='clear'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='008'

POWERLEVEL9K_HOST_FOREGROUND="grey"
POWERLEVEL9K_HOST_BACKGROUND="clear"
POWERLEVEL9K_HOST_ICON=""
POWERLEVEL9K_USER_ICON=""

POWERLEVEL9K_USER_BACKGROUND="clear"

POWERLEVEL9K_DIR_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="008"
POWERLEVEL9K_DIR_FOREGROUND='010'
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="012"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="012"

POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{008}/%F{cyan}"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"
POWERLEVEL9K_ETC_ICON=""

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"

POWERLEVEL9K_GO_ICON="\uf7b7"
POWERLEVEL9K_GO_VERSION_BACKGROUND='clear'
POWERLEVEL9K_GO_VERSION_FOREGROUND='081'

#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\uf460%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\u2e2b%F{008}'
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='-'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{237}┌%F{clear}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{237}└%F{clear} "


POWERLEVEL9K_NVM_BACKGROUND='clear'
POWERLEVEL9K_NVM_FOREGROUND='green'

POWERLEVEL9K_OS_ICON_BACKGROUND='clear'
POWERLEVEL9K_OS_ICON_FOREGROUND='cyan'

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true


typeset -g POWERLEVEL9K_STATUS_{,OK_,ERROR_}BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="001"
POWERLEVEL9K_CARRIAGE_RETURN_ICON="\uf071"

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m}"

typeset -g POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_BACKGROUND='clear'
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED}_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
